FROM golang:1.14

WORKDIR /go/src/app

COPY go.mod .
COPY go.sum .
COPY protos protos
COPY gateway_service gateway_service

RUN go build -o gateway-service gateway_service/*.go

CMD ["/go/src/app/gateway-service"]
