FROM golang:1.14

WORKDIR /go/src/app

COPY go.mod .
COPY go.sum .
COPY tools tools
COPY protos protos
COPY users_service users_service

RUN go build -o users-service users_service/*.go

COPY compose-conf.json .

CMD ["/go/src/app/users-service", "-config", "/go/src/app/compose-conf.json"]
