version: '3'

services:
  postgres:
    image: "postgres:alpine"
    env_file:
      - postgres.env
    volumes:
      - persistent-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - persistent-data:/var/lib/redis/data/

  nats:
    image: 'nats:alpine'
    command: "--user user --pass password"
    ports:
      - "8222:8222"
      - "4222:4222"
    hostname: nats-server

  users:
    build:
      context: .
      dockerfile: Dockerfile.users
    depends_on:
      - postgres
      - redis
      - nats

volumes:
  persistent-data:
