// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/tweets.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Tweet struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId             int64    `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Creator              string   `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreationTimestamp    int64    `protobuf:"varint,5,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tweet) Reset()         { *m = Tweet{} }
func (m *Tweet) String() string { return proto.CompactTextString(m) }
func (*Tweet) ProtoMessage()    {}
func (*Tweet) Descriptor() ([]byte, []int) {
	return fileDescriptor_a92c6f5e33d78274, []int{0}
}

func (m *Tweet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tweet.Unmarshal(m, b)
}
func (m *Tweet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tweet.Marshal(b, m, deterministic)
}
func (m *Tweet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tweet.Merge(m, src)
}
func (m *Tweet) XXX_Size() int {
	return xxx_messageInfo_Tweet.Size(m)
}
func (m *Tweet) XXX_DiscardUnknown() {
	xxx_messageInfo_Tweet.DiscardUnknown(m)
}

var xxx_messageInfo_Tweet proto.InternalMessageInfo

func (m *Tweet) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Tweet) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *Tweet) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Tweet) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Tweet) GetCreationTimestamp() int64 {
	if m != nil {
		return m.CreationTimestamp
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_a92c6f5e33d78274, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type CreateTweetRequest struct {
	ParentId             int64    `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Creator              string   `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTweetRequest) Reset()         { *m = CreateTweetRequest{} }
func (m *CreateTweetRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTweetRequest) ProtoMessage()    {}
func (*CreateTweetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a92c6f5e33d78274, []int{2}
}

func (m *CreateTweetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTweetRequest.Unmarshal(m, b)
}
func (m *CreateTweetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTweetRequest.Marshal(b, m, deterministic)
}
func (m *CreateTweetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTweetRequest.Merge(m, src)
}
func (m *CreateTweetRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTweetRequest.Size(m)
}
func (m *CreateTweetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTweetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTweetRequest proto.InternalMessageInfo

func (m *CreateTweetRequest) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *CreateTweetRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *CreateTweetRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type GetTweetsRequest struct {
	Tweets               []int64  `protobuf:"varint,1,rep,packed,name=tweets,proto3" json:"tweets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTweetsRequest) Reset()         { *m = GetTweetsRequest{} }
func (m *GetTweetsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTweetsRequest) ProtoMessage()    {}
func (*GetTweetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a92c6f5e33d78274, []int{3}
}

func (m *GetTweetsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTweetsRequest.Unmarshal(m, b)
}
func (m *GetTweetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTweetsRequest.Marshal(b, m, deterministic)
}
func (m *GetTweetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTweetsRequest.Merge(m, src)
}
func (m *GetTweetsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTweetsRequest.Size(m)
}
func (m *GetTweetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTweetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTweetsRequest proto.InternalMessageInfo

func (m *GetTweetsRequest) GetTweets() []int64 {
	if m != nil {
		return m.Tweets
	}
	return nil
}

type GetTweetsReply struct {
	// Types that are valid to be assigned to Reply:
	//	*GetTweetsReply_Tweet
	//	*GetTweetsReply_Error
	Reply                isGetTweetsReply_Reply `protobuf_oneof:"reply"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetTweetsReply) Reset()         { *m = GetTweetsReply{} }
func (m *GetTweetsReply) String() string { return proto.CompactTextString(m) }
func (*GetTweetsReply) ProtoMessage()    {}
func (*GetTweetsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a92c6f5e33d78274, []int{4}
}

func (m *GetTweetsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTweetsReply.Unmarshal(m, b)
}
func (m *GetTweetsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTweetsReply.Marshal(b, m, deterministic)
}
func (m *GetTweetsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTweetsReply.Merge(m, src)
}
func (m *GetTweetsReply) XXX_Size() int {
	return xxx_messageInfo_GetTweetsReply.Size(m)
}
func (m *GetTweetsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTweetsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetTweetsReply proto.InternalMessageInfo

type isGetTweetsReply_Reply interface {
	isGetTweetsReply_Reply()
}

type GetTweetsReply_Tweet struct {
	Tweet *Tweet `protobuf:"bytes,1,opt,name=tweet,proto3,oneof"`
}

type GetTweetsReply_Error struct {
	Error bool `protobuf:"varint,2,opt,name=error,proto3,oneof"`
}

func (*GetTweetsReply_Tweet) isGetTweetsReply_Reply() {}

func (*GetTweetsReply_Error) isGetTweetsReply_Reply() {}

func (m *GetTweetsReply) GetReply() isGetTweetsReply_Reply {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (m *GetTweetsReply) GetTweet() *Tweet {
	if x, ok := m.GetReply().(*GetTweetsReply_Tweet); ok {
		return x.Tweet
	}
	return nil
}

func (m *GetTweetsReply) GetError() bool {
	if x, ok := m.GetReply().(*GetTweetsReply_Error); ok {
		return x.Error
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetTweetsReply) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetTweetsReply_Tweet)(nil),
		(*GetTweetsReply_Error)(nil),
	}
}

type EditTweetRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditTweetRequest) Reset()         { *m = EditTweetRequest{} }
func (m *EditTweetRequest) String() string { return proto.CompactTextString(m) }
func (*EditTweetRequest) ProtoMessage()    {}
func (*EditTweetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a92c6f5e33d78274, []int{5}
}

func (m *EditTweetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditTweetRequest.Unmarshal(m, b)
}
func (m *EditTweetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditTweetRequest.Marshal(b, m, deterministic)
}
func (m *EditTweetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditTweetRequest.Merge(m, src)
}
func (m *EditTweetRequest) XXX_Size() int {
	return xxx_messageInfo_EditTweetRequest.Size(m)
}
func (m *EditTweetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditTweetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditTweetRequest proto.InternalMessageInfo

func (m *EditTweetRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EditTweetRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type DeleteTweetsRequest struct {
	Id                   []int64  `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTweetsRequest) Reset()         { *m = DeleteTweetsRequest{} }
func (m *DeleteTweetsRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTweetsRequest) ProtoMessage()    {}
func (*DeleteTweetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a92c6f5e33d78274, []int{6}
}

func (m *DeleteTweetsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTweetsRequest.Unmarshal(m, b)
}
func (m *DeleteTweetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTweetsRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTweetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTweetsRequest.Merge(m, src)
}
func (m *DeleteTweetsRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTweetsRequest.Size(m)
}
func (m *DeleteTweetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTweetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTweetsRequest proto.InternalMessageInfo

func (m *DeleteTweetsRequest) GetId() []int64 {
	if m != nil {
		return m.Id
	}
	return nil
}

func init() {
	proto.RegisterType((*Tweet)(nil), "tweets.Tweet")
	proto.RegisterType((*Empty)(nil), "tweets.Empty")
	proto.RegisterType((*CreateTweetRequest)(nil), "tweets.CreateTweetRequest")
	proto.RegisterType((*GetTweetsRequest)(nil), "tweets.GetTweetsRequest")
	proto.RegisterType((*GetTweetsReply)(nil), "tweets.GetTweetsReply")
	proto.RegisterType((*EditTweetRequest)(nil), "tweets.EditTweetRequest")
	proto.RegisterType((*DeleteTweetsRequest)(nil), "tweets.DeleteTweetsRequest")
}

func init() {
	proto.RegisterFile("protos/tweets.proto", fileDescriptor_a92c6f5e33d78274)
}

var fileDescriptor_a92c6f5e33d78274 = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x5d, 0x6b, 0x13, 0x41,
	0x14, 0x75, 0xb2, 0xdd, 0xa4, 0xb9, 0xc1, 0x52, 0x6f, 0x21, 0x0c, 0xe9, 0x4b, 0x58, 0x28, 0x04,
	0x21, 0x89, 0x54, 0x11, 0xc5, 0x87, 0x62, 0xb5, 0xa8, 0xaf, 0x4b, 0x1f, 0xc4, 0x97, 0x90, 0xee,
	0x5e, 0x74, 0x70, 0x77, 0x67, 0x9d, 0xb9, 0x31, 0xc6, 0x3f, 0xe2, 0x1f, 0xf5, 0x07, 0xc8, 0xce,
	0xee, 0xc4, 0x64, 0xdb, 0x3c, 0xcd, 0xdc, 0x7b, 0xee, 0xc7, 0x39, 0x67, 0x18, 0x38, 0x2b, 0x8d,
	0x66, 0x6d, 0xe7, 0xbc, 0x26, 0x62, 0x3b, 0x73, 0x11, 0x76, 0xeb, 0x28, 0xfa, 0x23, 0x20, 0xbc,
	0xad, 0xae, 0x78, 0x02, 0x1d, 0x95, 0x4a, 0x31, 0x16, 0x93, 0x20, 0xee, 0xa8, 0x14, 0xcf, 0xa1,
	0x5f, 0x2e, 0x0d, 0x15, 0xbc, 0x50, 0xa9, 0xec, 0xb8, 0xf4, 0x71, 0x9d, 0xf8, 0x94, 0xa2, 0x84,
	0x5e, 0x62, 0x68, 0xc9, 0xda, 0xc8, 0x60, 0x2c, 0x26, 0xfd, 0xd8, 0x87, 0x0e, 0xd1, 0x05, 0x53,
	0xc1, 0xf2, 0xa8, 0x41, 0xea, 0x10, 0xa7, 0x80, 0xae, 0x48, 0xe9, 0x62, 0xc1, 0x2a, 0x27, 0xcb,
	0xcb, 0xbc, 0x94, 0xa1, 0x9b, 0xfc, 0xc4, 0x23, 0xb7, 0x1e, 0x88, 0x7a, 0x10, 0xde, 0xe4, 0x25,
	0x6f, 0x22, 0x02, 0x7c, 0x57, 0xa1, 0xe4, 0x78, 0xc6, 0xf4, 0x63, 0x45, 0x96, 0xf7, 0xe9, 0x89,
	0xc3, 0xf4, 0x3a, 0x07, 0xe9, 0x05, 0x7b, 0xf4, 0xa2, 0xa7, 0x70, 0xfa, 0x81, 0xd8, 0xed, 0xb0,
	0x7e, 0xc9, 0x10, 0x1a, 0x9f, 0xa4, 0x18, 0x07, 0x93, 0x20, 0xf6, 0xae, 0x7d, 0x86, 0x93, 0x9d,
	0xda, 0x32, 0xdb, 0xe0, 0x05, 0x84, 0x0e, 0x73, 0x54, 0x06, 0x97, 0x8f, 0x67, 0x8d, 0xdb, 0xae,
	0xe6, 0xe3, 0xa3, 0xb8, 0x46, 0x71, 0x08, 0x21, 0x19, 0xd3, 0xd0, 0x3a, 0xae, 0xf2, 0x2e, 0xbc,
	0xee, 0x41, 0x68, 0xaa, 0x39, 0xd1, 0x4b, 0x38, 0xbd, 0x49, 0x15, 0xef, 0x49, 0x6d, 0xbf, 0x0c,
	0xc2, 0x11, 0xd3, 0x2f, 0x6e, 0xa4, 0xb9, 0x7b, 0x74, 0x01, 0x67, 0xef, 0x29, 0xa3, 0xc6, 0x24,
	0xdb, 0x6e, 0x0d, 0xea, 0xd6, 0xcb, 0xbf, 0x02, 0xba, 0x75, 0x05, 0xbe, 0x82, 0xc1, 0x8e, 0xad,
	0x38, 0xf2, 0x8c, 0xef, 0x7b, 0x3d, 0xda, 0xaa, 0x71, 0x0f, 0x82, 0x57, 0xd0, 0xdf, 0xaa, 0x47,
	0xe9, 0xb1, 0xb6, 0x79, 0xa3, 0xe1, 0x03, 0x48, 0x99, 0x6d, 0x9e, 0x09, 0x7c, 0x01, 0xfd, 0xad,
	0xc8, 0xff, 0x03, 0xda, 0xba, 0xdb, 0x6b, 0x5f, 0xc3, 0x60, 0x47, 0x22, 0x9e, 0x7b, 0xf4, 0x01,
	0xdd, 0xad, 0xd6, 0xeb, 0xb7, 0x5f, 0xae, 0xbe, 0x2a, 0xfe, 0xb6, 0xba, 0x9b, 0x25, 0x3a, 0x9f,
	0x67, 0x8a, 0x8c, 0xfe, 0x3d, 0x4f, 0x55, 0x69, 0xa7, 0x89, 0x5e, 0x19, 0x4b, 0x6b, 0x6d, 0xbe,
	0x4f, 0x79, 0xad, 0x98, 0xc9, 0x34, 0xff, 0x64, 0x61, 0xc9, 0xfc, 0x54, 0x09, 0xbd, 0xa9, 0x7f,
	0xcf, 0x5d, 0xd7, 0x9d, 0xcf, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x1a, 0x05, 0x91, 0x4e,
	0x03, 0x00, 0x00,
}
