// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Role int32

const (
	Role_Follower Role = 0
	Role_Followed Role = 1
)

var Role_name = map[int32]string{
	0: "Follower",
	1: "Followed",
}

var Role_value = map[string]int32{
	"Follower": 0,
	"Followed": 1,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{0}
}

type User struct {
	Username              string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Firstname             string   `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname              string   `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Description           string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	RegistrationTimestamp int64    `protobuf:"varint,5,opt,name=registration_timestamp,json=registrationTimestamp,proto3" json:"registration_timestamp,omitempty"`
	Followers             []string `protobuf:"bytes,6,rep,name=followers,proto3" json:"followers,omitempty"`
	Following             []string `protobuf:"bytes,7,rep,name=following,proto3" json:"following,omitempty"`
	Tweets                []int64  `protobuf:"varint,8,rep,packed,name=tweets,proto3" json:"tweets,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *User) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *User) GetRegistrationTimestamp() int64 {
	if m != nil {
		return m.RegistrationTimestamp
	}
	return 0
}

func (m *User) GetFollowers() []string {
	if m != nil {
		return m.Followers
	}
	return nil
}

func (m *User) GetFollowing() []string {
	if m != nil {
		return m.Following
	}
	return nil
}

func (m *User) GetTweets() []int64 {
	if m != nil {
		return m.Tweets
	}
	return nil
}

type CreateRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Firstname            string   `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateRequest) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *CreateRequest) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *CreateRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type DeleteRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{2}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetSummaryRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSummaryRequest) Reset()         { *m = GetSummaryRequest{} }
func (m *GetSummaryRequest) String() string { return proto.CompactTextString(m) }
func (*GetSummaryRequest) ProtoMessage()    {}
func (*GetSummaryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{3}
}

func (m *GetSummaryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSummaryRequest.Unmarshal(m, b)
}
func (m *GetSummaryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSummaryRequest.Marshal(b, m, deterministic)
}
func (m *GetSummaryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSummaryRequest.Merge(m, src)
}
func (m *GetSummaryRequest) XXX_Size() int {
	return xxx_messageInfo_GetSummaryRequest.Size(m)
}
func (m *GetSummaryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSummaryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSummaryRequest proto.InternalMessageInfo

func (m *GetSummaryRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetSummaryReply struct {
	Username              string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Firstname             string   `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname              string   `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Description           string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	RegistrationTimestamp int64    `protobuf:"varint,5,opt,name=registration_timestamp,json=registrationTimestamp,proto3" json:"registration_timestamp,omitempty"`
	FollowersCount        int64    `protobuf:"varint,6,opt,name=followers_count,json=followersCount,proto3" json:"followers_count,omitempty"`
	FollowingCount        int64    `protobuf:"varint,7,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	TweetsCount           int64    `protobuf:"varint,8,opt,name=tweets_count,json=tweetsCount,proto3" json:"tweets_count,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *GetSummaryReply) Reset()         { *m = GetSummaryReply{} }
func (m *GetSummaryReply) String() string { return proto.CompactTextString(m) }
func (*GetSummaryReply) ProtoMessage()    {}
func (*GetSummaryReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{4}
}

func (m *GetSummaryReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSummaryReply.Unmarshal(m, b)
}
func (m *GetSummaryReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSummaryReply.Marshal(b, m, deterministic)
}
func (m *GetSummaryReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSummaryReply.Merge(m, src)
}
func (m *GetSummaryReply) XXX_Size() int {
	return xxx_messageInfo_GetSummaryReply.Size(m)
}
func (m *GetSummaryReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSummaryReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetSummaryReply proto.InternalMessageInfo

func (m *GetSummaryReply) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetSummaryReply) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *GetSummaryReply) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *GetSummaryReply) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetSummaryReply) GetRegistrationTimestamp() int64 {
	if m != nil {
		return m.RegistrationTimestamp
	}
	return 0
}

func (m *GetSummaryReply) GetFollowersCount() int64 {
	if m != nil {
		return m.FollowersCount
	}
	return 0
}

func (m *GetSummaryReply) GetFollowingCount() int64 {
	if m != nil {
		return m.FollowingCount
	}
	return 0
}

func (m *GetSummaryReply) GetTweetsCount() int64 {
	if m != nil {
		return m.TweetsCount
	}
	return 0
}

type GetUsersRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Role                 Role     `protobuf:"varint,2,opt,name=role,proto3,enum=Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersRequest) Reset()         { *m = GetUsersRequest{} }
func (m *GetUsersRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersRequest) ProtoMessage()    {}
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{5}
}

func (m *GetUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersRequest.Unmarshal(m, b)
}
func (m *GetUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersRequest.Marshal(b, m, deterministic)
}
func (m *GetUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersRequest.Merge(m, src)
}
func (m *GetUsersRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersRequest.Size(m)
}
func (m *GetUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersRequest proto.InternalMessageInfo

func (m *GetUsersRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetUsersRequest) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_Follower
}

type GetUsersReply struct {
	// Types that are valid to be assigned to Reply:
	//	*GetUsersReply_User
	//	*GetUsersReply_Error
	Reply                isGetUsersReply_Reply `protobuf_oneof:"reply"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetUsersReply) Reset()         { *m = GetUsersReply{} }
func (m *GetUsersReply) String() string { return proto.CompactTextString(m) }
func (*GetUsersReply) ProtoMessage()    {}
func (*GetUsersReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{6}
}

func (m *GetUsersReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersReply.Unmarshal(m, b)
}
func (m *GetUsersReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersReply.Marshal(b, m, deterministic)
}
func (m *GetUsersReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersReply.Merge(m, src)
}
func (m *GetUsersReply) XXX_Size() int {
	return xxx_messageInfo_GetUsersReply.Size(m)
}
func (m *GetUsersReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersReply proto.InternalMessageInfo

type isGetUsersReply_Reply interface {
	isGetUsersReply_Reply()
}

type GetUsersReply_User struct {
	User *User `protobuf:"bytes,1,opt,name=user,proto3,oneof"`
}

type GetUsersReply_Error struct {
	Error bool `protobuf:"varint,2,opt,name=error,proto3,oneof"`
}

func (*GetUsersReply_User) isGetUsersReply_Reply() {}

func (*GetUsersReply_Error) isGetUsersReply_Reply() {}

func (m *GetUsersReply) GetReply() isGetUsersReply_Reply {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (m *GetUsersReply) GetUser() *User {
	if x, ok := m.GetReply().(*GetUsersReply_User); ok {
		return x.User
	}
	return nil
}

func (m *GetUsersReply) GetError() bool {
	if x, ok := m.GetReply().(*GetUsersReply_Error); ok {
		return x.Error
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetUsersReply) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetUsersReply_User)(nil),
		(*GetUsersReply_Error)(nil),
	}
}

type FollowRequest struct {
	Follower             string   `protobuf:"bytes,1,opt,name=follower,proto3" json:"follower,omitempty"`
	Followed             string   `protobuf:"bytes,2,opt,name=followed,proto3" json:"followed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowRequest) Reset()         { *m = FollowRequest{} }
func (m *FollowRequest) String() string { return proto.CompactTextString(m) }
func (*FollowRequest) ProtoMessage()    {}
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{7}
}

func (m *FollowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowRequest.Unmarshal(m, b)
}
func (m *FollowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowRequest.Marshal(b, m, deterministic)
}
func (m *FollowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowRequest.Merge(m, src)
}
func (m *FollowRequest) XXX_Size() int {
	return xxx_messageInfo_FollowRequest.Size(m)
}
func (m *FollowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FollowRequest proto.InternalMessageInfo

func (m *FollowRequest) GetFollower() string {
	if m != nil {
		return m.Follower
	}
	return ""
}

func (m *FollowRequest) GetFollowed() string {
	if m != nil {
		return m.Followed
	}
	return ""
}

type OnTweetCreatedRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	TweetId              int64    `protobuf:"varint,2,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnTweetCreatedRequest) Reset()         { *m = OnTweetCreatedRequest{} }
func (m *OnTweetCreatedRequest) String() string { return proto.CompactTextString(m) }
func (*OnTweetCreatedRequest) ProtoMessage()    {}
func (*OnTweetCreatedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{8}
}

func (m *OnTweetCreatedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnTweetCreatedRequest.Unmarshal(m, b)
}
func (m *OnTweetCreatedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnTweetCreatedRequest.Marshal(b, m, deterministic)
}
func (m *OnTweetCreatedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnTweetCreatedRequest.Merge(m, src)
}
func (m *OnTweetCreatedRequest) XXX_Size() int {
	return xxx_messageInfo_OnTweetCreatedRequest.Size(m)
}
func (m *OnTweetCreatedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OnTweetCreatedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OnTweetCreatedRequest proto.InternalMessageInfo

func (m *OnTweetCreatedRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *OnTweetCreatedRequest) GetTweetId() int64 {
	if m != nil {
		return m.TweetId
	}
	return 0
}

type OnTweetsDeletedRequest struct {
	TweetId              []int64  `protobuf:"varint,1,rep,packed,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnTweetsDeletedRequest) Reset()         { *m = OnTweetsDeletedRequest{} }
func (m *OnTweetsDeletedRequest) String() string { return proto.CompactTextString(m) }
func (*OnTweetsDeletedRequest) ProtoMessage()    {}
func (*OnTweetsDeletedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{9}
}

func (m *OnTweetsDeletedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnTweetsDeletedRequest.Unmarshal(m, b)
}
func (m *OnTweetsDeletedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnTweetsDeletedRequest.Marshal(b, m, deterministic)
}
func (m *OnTweetsDeletedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnTweetsDeletedRequest.Merge(m, src)
}
func (m *OnTweetsDeletedRequest) XXX_Size() int {
	return xxx_messageInfo_OnTweetsDeletedRequest.Size(m)
}
func (m *OnTweetsDeletedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OnTweetsDeletedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OnTweetsDeletedRequest proto.InternalMessageInfo

func (m *OnTweetsDeletedRequest) GetTweetId() []int64 {
	if m != nil {
		return m.TweetId
	}
	return nil
}

func init() {
	proto.RegisterEnum("Role", Role_name, Role_value)
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*GetSummaryRequest)(nil), "GetSummaryRequest")
	proto.RegisterType((*GetSummaryReply)(nil), "GetSummaryReply")
	proto.RegisterType((*GetUsersRequest)(nil), "GetUsersRequest")
	proto.RegisterType((*GetUsersReply)(nil), "GetUsersReply")
	proto.RegisterType((*FollowRequest)(nil), "FollowRequest")
	proto.RegisterType((*OnTweetCreatedRequest)(nil), "OnTweetCreatedRequest")
	proto.RegisterType((*OnTweetsDeletedRequest)(nil), "OnTweetsDeletedRequest")
}

func init() {
	proto.RegisterFile("users.proto", fileDescriptor_030765f334c86cea)
}

var fileDescriptor_030765f334c86cea = []byte{
	// 584 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0xe3, 0xd8, 0x71, 0x27, 0x8d, 0x1b, 0x56, 0x6a, 0x30, 0x81, 0x83, 0xb1, 0x90, 0x88,
	0x40, 0x5a, 0xaa, 0x54, 0x5c, 0xe0, 0xd6, 0x42, 0x9b, 0x1e, 0x00, 0xc9, 0xb4, 0x17, 0x2e, 0x91,
	0x69, 0x36, 0x91, 0x25, 0x7f, 0x84, 0xdd, 0x8d, 0xaa, 0xfc, 0x02, 0xc4, 0x0f, 0xe2, 0x57, 0xf1,
	0x27, 0xd0, 0xce, 0xae, 0x1d, 0xa7, 0x54, 0x28, 0x37, 0xc4, 0x29, 0x7a, 0xf3, 0xde, 0x5b, 0xcd,
	0xce, 0xdb, 0x89, 0xa1, 0xbb, 0x12, 0x8c, 0x0b, 0xba, 0xe4, 0xa5, 0x2c, 0x87, 0xdd, 0x95, 0x4c,
	0x33, 0x03, 0xa2, 0x1f, 0x2d, 0x68, 0x5f, 0x0b, 0xc6, 0xc9, 0x10, 0x3c, 0x25, 0x2a, 0x92, 0x9c,
	0x05, 0x56, 0x68, 0x8d, 0xf6, 0xe3, 0x1a, 0x93, 0x27, 0xb0, 0x3f, 0x4f, 0xb9, 0x90, 0x48, 0xb6,
	0x90, 0xdc, 0x14, 0x94, 0x33, 0x4b, 0x0c, 0x69, 0x6b, 0x67, 0x85, 0x49, 0x08, 0xdd, 0x19, 0x13,
	0x37, 0x3c, 0x5d, 0xca, 0xb4, 0x2c, 0x82, 0x36, 0xd2, 0xcd, 0x12, 0x79, 0x0d, 0x03, 0xce, 0x16,
	0xa9, 0x90, 0x3c, 0x51, 0x78, 0x2a, 0xd3, 0x9c, 0x09, 0x99, 0xe4, 0xcb, 0xc0, 0x09, 0xad, 0x91,
	0x1d, 0x1f, 0x35, 0xd9, 0xab, 0x8a, 0xc4, 0x96, 0xca, 0x2c, 0x2b, 0x6f, 0x19, 0x17, 0x81, 0x1b,
	0xda, 0xd8, 0x52, 0x55, 0xd8, 0xb0, 0x69, 0xb1, 0x08, 0x3a, 0x4d, 0x36, 0x2d, 0x16, 0x64, 0x00,
	0xae, 0xbc, 0x65, 0x4c, 0x8a, 0xc0, 0x0b, 0xed, 0x91, 0x1d, 0x1b, 0x14, 0x7d, 0xb7, 0xa0, 0x77,
	0xc6, 0x59, 0x22, 0x59, 0xcc, 0xbe, 0xad, 0x98, 0x90, 0xff, 0x6a, 0x28, 0xd1, 0x4b, 0xe8, 0xbd,
	0x63, 0x19, 0xdb, 0xa9, 0x91, 0xe8, 0x15, 0x3c, 0xb8, 0x60, 0xf2, 0xf3, 0x2a, 0xcf, 0x13, 0xbe,
	0xde, 0xc5, 0xf0, 0xb3, 0x05, 0x87, 0x4d, 0xc7, 0x32, 0x5b, 0xff, 0x6f, 0xf1, 0x3f, 0x87, 0xc3,
	0x3a, 0xed, 0xe9, 0x4d, 0xb9, 0x2a, 0x64, 0xe0, 0xa2, 0xde, 0xaf, 0xcb, 0x67, 0xaa, 0xba, 0x11,
	0xa6, 0xc5, 0xc2, 0x08, 0x3b, 0x4d, 0x61, 0x5a, 0x2c, 0xb4, 0xf0, 0x29, 0x1c, 0xe8, 0x67, 0x60,
	0x54, 0x1e, 0xaa, 0xba, 0xba, 0x86, 0x92, 0x68, 0x82, 0x63, 0x53, 0xdb, 0x22, 0x76, 0x79, 0x20,
	0x8f, 0xa0, 0xcd, 0xcb, 0x4c, 0x4f, 0xcc, 0x1f, 0x3b, 0x34, 0x2e, 0x33, 0x16, 0x63, 0x29, 0xfa,
	0x00, 0xbd, 0xcd, 0x49, 0x6a, 0xfc, 0x8f, 0xa1, 0xad, 0x7c, 0x78, 0x46, 0x77, 0xec, 0x50, 0x45,
	0x4d, 0xf6, 0x62, 0x2c, 0x92, 0x01, 0x38, 0x8c, 0xf3, 0x92, 0xe3, 0x49, 0xde, 0x64, 0x2f, 0xd6,
	0xf0, 0xb4, 0x03, 0x0e, 0x57, 0xee, 0xe8, 0x02, 0x7a, 0xe7, 0x78, 0x9b, 0x46, 0x5b, 0xd5, 0x1c,
	0xaa, 0xb6, 0x2a, 0xdc, 0xe0, 0x66, 0x26, 0xcc, 0x1a, 0x47, 0x1f, 0xe1, 0xe8, 0x53, 0x71, 0xa5,
	0xae, 0xac, 0xf7, 0x60, 0xb6, 0xdb, 0x3d, 0x3d, 0x9c, 0xd2, 0x34, 0xd5, 0x07, 0xda, 0x71, 0x07,
	0xf1, 0xe5, 0x2c, 0x3a, 0x81, 0x81, 0x39, 0x4f, 0xe8, 0xf7, 0x5c, 0x1f, 0xd8, 0x34, 0x59, 0xb8,
	0x85, 0x95, 0xe9, 0x45, 0x04, 0x6d, 0x35, 0x2a, 0x72, 0x00, 0xde, 0xb9, 0x69, 0xba, 0xbf, 0xd7,
	0x40, 0xb3, 0xbe, 0x35, 0xfe, 0xd5, 0x02, 0x07, 0xc7, 0x47, 0x9e, 0x01, 0xe8, 0x5e, 0xf1, 0x5f,
	0xcc, 0xa7, 0x5b, 0x0b, 0x3c, 0x74, 0xe9, 0xfb, 0x7c, 0x29, 0xd7, 0x4a, 0xa5, 0x1b, 0x30, 0xaa,
	0xad, 0xed, 0xaa, 0x55, 0x6f, 0x80, 0x98, 0x58, 0x2e, 0x8b, 0x79, 0x69, 0xf6, 0x83, 0x10, 0xfa,
	0xc7, 0x7a, 0x0d, 0xfb, 0xf4, 0xee, 0x02, 0x51, 0xf0, 0xaa, 0x48, 0x09, 0xb2, 0xcd, 0x77, 0x32,
	0xf4, 0xe9, 0x56, 0xde, 0xc7, 0x16, 0x09, 0xc1, 0xd5, 0xf7, 0x21, 0x3e, 0xdd, 0x0a, 0xaf, 0xee,
	0x26, 0x02, 0xef, 0xba, 0x98, 0xff, 0x5d, 0x73, 0x0c, 0xfe, 0x76, 0x60, 0x64, 0x40, 0xef, 0x4d,
	0xb0, 0x76, 0x8c, 0xe1, 0xf0, 0x4e, 0x24, 0xe4, 0x21, 0xbd, 0x3f, 0xa4, 0xca, 0x73, 0x0a, 0x5f,
	0x3c, 0xfa, 0x16, 0xbf, 0x17, 0xe2, 0xab, 0x8b, 0xbf, 0x27, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x86, 0xb1, 0x2d, 0xfb, 0x53, 0x06, 0x00, 0x00,
}
