// Code generated by protoc-gen-go. DO NOT EDIT.
// source: utils.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NatsMessage_Command int32

const (
	NatsMessage_DeleteUser   NatsMessage_Command = 0
	NatsMessage_CreateTweet  NatsMessage_Command = 1
	NatsMessage_DeleteTweets NatsMessage_Command = 2
)

var NatsMessage_Command_name = map[int32]string{
	0: "DeleteUser",
	1: "CreateTweet",
	2: "DeleteTweets",
}

var NatsMessage_Command_value = map[string]int32{
	"DeleteUser":   0,
	"CreateTweet":  1,
	"DeleteTweets": 2,
}

func (x NatsMessage_Command) String() string {
	return proto.EnumName(NatsMessage_Command_name, int32(x))
}

func (NatsMessage_Command) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c91c651f4717a5f2, []int{4, 0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_c91c651f4717a5f2, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type NatsDeleteUserMessage struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Tweets               []int64  `protobuf:"varint,2,rep,packed,name=tweets,proto3" json:"tweets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NatsDeleteUserMessage) Reset()         { *m = NatsDeleteUserMessage{} }
func (m *NatsDeleteUserMessage) String() string { return proto.CompactTextString(m) }
func (*NatsDeleteUserMessage) ProtoMessage()    {}
func (*NatsDeleteUserMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c91c651f4717a5f2, []int{1}
}

func (m *NatsDeleteUserMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NatsDeleteUserMessage.Unmarshal(m, b)
}
func (m *NatsDeleteUserMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NatsDeleteUserMessage.Marshal(b, m, deterministic)
}
func (m *NatsDeleteUserMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NatsDeleteUserMessage.Merge(m, src)
}
func (m *NatsDeleteUserMessage) XXX_Size() int {
	return xxx_messageInfo_NatsDeleteUserMessage.Size(m)
}
func (m *NatsDeleteUserMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NatsDeleteUserMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NatsDeleteUserMessage proto.InternalMessageInfo

func (m *NatsDeleteUserMessage) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *NatsDeleteUserMessage) GetTweets() []int64 {
	if m != nil {
		return m.Tweets
	}
	return nil
}

type NatsCreateTweetMessage struct {
	TweetId              int64    `protobuf:"varint,1,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
	ParentTweetId        int64    `protobuf:"varint,2,opt,name=parent_tweet_id,json=parentTweetId,proto3" json:"parent_tweet_id,omitempty"`
	Creator              string   `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NatsCreateTweetMessage) Reset()         { *m = NatsCreateTweetMessage{} }
func (m *NatsCreateTweetMessage) String() string { return proto.CompactTextString(m) }
func (*NatsCreateTweetMessage) ProtoMessage()    {}
func (*NatsCreateTweetMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c91c651f4717a5f2, []int{2}
}

func (m *NatsCreateTweetMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NatsCreateTweetMessage.Unmarshal(m, b)
}
func (m *NatsCreateTweetMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NatsCreateTweetMessage.Marshal(b, m, deterministic)
}
func (m *NatsCreateTweetMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NatsCreateTweetMessage.Merge(m, src)
}
func (m *NatsCreateTweetMessage) XXX_Size() int {
	return xxx_messageInfo_NatsCreateTweetMessage.Size(m)
}
func (m *NatsCreateTweetMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NatsCreateTweetMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NatsCreateTweetMessage proto.InternalMessageInfo

func (m *NatsCreateTweetMessage) GetTweetId() int64 {
	if m != nil {
		return m.TweetId
	}
	return 0
}

func (m *NatsCreateTweetMessage) GetParentTweetId() int64 {
	if m != nil {
		return m.ParentTweetId
	}
	return 0
}

func (m *NatsCreateTweetMessage) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *NatsCreateTweetMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type NatsDeleteTweetsMessage struct {
	Tweets               []int64  `protobuf:"varint,1,rep,packed,name=tweets,proto3" json:"tweets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NatsDeleteTweetsMessage) Reset()         { *m = NatsDeleteTweetsMessage{} }
func (m *NatsDeleteTweetsMessage) String() string { return proto.CompactTextString(m) }
func (*NatsDeleteTweetsMessage) ProtoMessage()    {}
func (*NatsDeleteTweetsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c91c651f4717a5f2, []int{3}
}

func (m *NatsDeleteTweetsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NatsDeleteTweetsMessage.Unmarshal(m, b)
}
func (m *NatsDeleteTweetsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NatsDeleteTweetsMessage.Marshal(b, m, deterministic)
}
func (m *NatsDeleteTweetsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NatsDeleteTweetsMessage.Merge(m, src)
}
func (m *NatsDeleteTweetsMessage) XXX_Size() int {
	return xxx_messageInfo_NatsDeleteTweetsMessage.Size(m)
}
func (m *NatsDeleteTweetsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NatsDeleteTweetsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NatsDeleteTweetsMessage proto.InternalMessageInfo

func (m *NatsDeleteTweetsMessage) GetTweets() []int64 {
	if m != nil {
		return m.Tweets
	}
	return nil
}

type NatsMessage struct {
	Command              NatsMessage_Command `protobuf:"varint,1,opt,name=command,proto3,enum=NatsMessage_Command" json:"command,omitempty"`
	Message              []byte              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NatsMessage) Reset()         { *m = NatsMessage{} }
func (m *NatsMessage) String() string { return proto.CompactTextString(m) }
func (*NatsMessage) ProtoMessage()    {}
func (*NatsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c91c651f4717a5f2, []int{4}
}

func (m *NatsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NatsMessage.Unmarshal(m, b)
}
func (m *NatsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NatsMessage.Marshal(b, m, deterministic)
}
func (m *NatsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NatsMessage.Merge(m, src)
}
func (m *NatsMessage) XXX_Size() int {
	return xxx_messageInfo_NatsMessage.Size(m)
}
func (m *NatsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NatsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NatsMessage proto.InternalMessageInfo

func (m *NatsMessage) GetCommand() NatsMessage_Command {
	if m != nil {
		return m.Command
	}
	return NatsMessage_DeleteUser
}

func (m *NatsMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterEnum("NatsMessage_Command", NatsMessage_Command_name, NatsMessage_Command_value)
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*NatsDeleteUserMessage)(nil), "NatsDeleteUserMessage")
	proto.RegisterType((*NatsCreateTweetMessage)(nil), "NatsCreateTweetMessage")
	proto.RegisterType((*NatsDeleteTweetsMessage)(nil), "NatsDeleteTweetsMessage")
	proto.RegisterType((*NatsMessage)(nil), "NatsMessage")
}

func init() {
	proto.RegisterFile("utils.proto", fileDescriptor_c91c651f4717a5f2)
}

var fileDescriptor_c91c651f4717a5f2 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x3f, 0x4f, 0xc3, 0x30,
	0x14, 0xc4, 0x71, 0x02, 0x4d, 0x78, 0x29, 0x6d, 0x64, 0x41, 0x09, 0x4c, 0x55, 0x06, 0xd4, 0x29,
	0x12, 0x30, 0xc2, 0x44, 0x61, 0x40, 0x08, 0x86, 0xa8, 0x2c, 0x2c, 0x95, 0xa1, 0x4f, 0xa8, 0x52,
	0xf3, 0x47, 0xf6, 0xab, 0x10, 0x9f, 0x82, 0x89, 0xef, 0x8b, 0xfc, 0x12, 0x37, 0x61, 0x8a, 0xce,
	0xf7, 0xcb, 0xe9, 0xce, 0x86, 0x68, 0x4b, 0xeb, 0x8d, 0xc9, 0x6a, 0x5d, 0x51, 0x95, 0x06, 0x70,
	0xf0, 0x50, 0xd4, 0xf4, 0x9d, 0x3e, 0xc1, 0xc9, 0x8b, 0x22, 0x73, 0x8f, 0x1b, 0x24, 0x7c, 0x35,
	0xa8, 0x9f, 0xd1, 0x18, 0xf5, 0x89, 0xf2, 0x1c, 0xc2, 0xad, 0x41, 0x5d, 0xaa, 0x02, 0x13, 0x31,
	0x15, 0xb3, 0xc3, 0x7c, 0xa7, 0xe5, 0x04, 0x06, 0xf4, 0x85, 0x48, 0x26, 0xf1, 0xa6, 0xfe, 0xcc,
	0xcf, 0x5b, 0x95, 0xfe, 0x08, 0x98, 0xd8, 0xb4, 0xb9, 0x46, 0x45, 0xb8, 0xb0, 0x87, 0x2e, 0xee,
	0x0c, 0x42, 0x86, 0x96, 0xeb, 0x15, 0xc7, 0xf9, 0x79, 0xc0, 0xfa, 0x71, 0x25, 0x2f, 0x60, 0x5c,
	0x2b, 0x8d, 0x25, 0x2d, 0x77, 0x84, 0xc7, 0xc4, 0x51, 0x73, 0xbc, 0x68, 0xb9, 0x04, 0x82, 0x0f,
	0x1b, 0x5c, 0xe9, 0xc4, 0xe7, 0x42, 0x4e, 0xb2, 0x53, 0x95, 0x84, 0x25, 0x25, 0xfb, 0xad, 0xd3,
	0xc8, 0xf4, 0x12, 0x4e, 0xbb, 0x79, 0x1c, 0x64, 0x5c, 0xa3, 0x6e, 0x84, 0xf8, 0x37, 0xe2, 0x57,
	0x40, 0x64, 0xff, 0x71, 0x5c, 0x66, 0xc3, 0x8b, 0x42, 0x95, 0x4d, 0xf1, 0xd1, 0xd5, 0x71, 0xd6,
	0xb3, 0xb3, 0x79, 0xe3, 0xe5, 0x0e, 0xb2, 0x65, 0x8a, 0xc6, 0xe3, 0x19, 0xc3, 0xdc, 0xc9, 0xf4,
	0x16, 0x82, 0x96, 0x96, 0x23, 0x80, 0xee, 0xca, 0xe3, 0x3d, 0x39, 0x86, 0xa8, 0x77, 0x69, 0xb1,
	0x90, 0x31, 0x0c, 0xfb, 0xa5, 0x63, 0xef, 0x0e, 0xde, 0xc2, 0xec, 0x86, 0x5f, 0xcf, 0xbc, 0x0f,
	0xf8, 0x7b, 0xfd, 0x17, 0x00, 0x00, 0xff, 0xff, 0x81, 0xf4, 0xeb, 0xb3, 0xd4, 0x01, 0x00, 0x00,
}
