// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Role int32

const (
	Role_Follower Role = 0
	Role_Followed Role = 1
)

var Role_name = map[int32]string{
	0: "Follower",
	1: "Followed",
}

var Role_value = map[string]int32{
	"Follower": 0,
	"Followed": 1,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{0}
}

type FollowRequest_Action int32

const (
	FollowRequest_Follow   FollowRequest_Action = 0
	FollowRequest_Unfollow FollowRequest_Action = 1
)

var FollowRequest_Action_name = map[int32]string{
	0: "Follow",
	1: "Unfollow",
}

var FollowRequest_Action_value = map[string]int32{
	"Follow":   0,
	"Unfollow": 1,
}

func (x FollowRequest_Action) String() string {
	return proto.EnumName(FollowRequest_Action_name, int32(x))
}

func (FollowRequest_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{8, 0}
}

type UpdateTweetsRequest_Action int32

const (
	UpdateTweetsRequest_Add UpdateTweetsRequest_Action = 0
	UpdateTweetsRequest_Del UpdateTweetsRequest_Action = 1
)

var UpdateTweetsRequest_Action_name = map[int32]string{
	0: "Add",
	1: "Del",
}

var UpdateTweetsRequest_Action_value = map[string]int32{
	"Add": 0,
	"Del": 1,
}

func (x UpdateTweetsRequest_Action) String() string {
	return proto.EnumName(UpdateTweetsRequest_Action_name, int32(x))
}

func (UpdateTweetsRequest_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{9, 0}
}

type GenericUpdateReply_Code int32

const (
	GenericUpdateReply_Ok    GenericUpdateReply_Code = 0
	GenericUpdateReply_Error GenericUpdateReply_Code = 1
)

var GenericUpdateReply_Code_name = map[int32]string{
	0: "Ok",
	1: "Error",
}

var GenericUpdateReply_Code_value = map[string]int32{
	"Ok":    0,
	"Error": 1,
}

func (x GenericUpdateReply_Code) String() string {
	return proto.EnumName(GenericUpdateReply_Code_name, int32(x))
}

func (GenericUpdateReply_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{10, 0}
}

type User struct {
	Username              string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Firstname             string   `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname              string   `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Description           string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	RegistrationTimestamp int64    `protobuf:"varint,5,opt,name=registration_timestamp,json=registrationTimestamp,proto3" json:"registration_timestamp,omitempty"`
	Followers             []string `protobuf:"bytes,6,rep,name=followers,proto3" json:"followers,omitempty"`
	Following             []string `protobuf:"bytes,7,rep,name=following,proto3" json:"following,omitempty"`
	Tweets                []int64  `protobuf:"varint,8,rep,packed,name=tweets,proto3" json:"tweets,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *User) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *User) GetRegistrationTimestamp() int64 {
	if m != nil {
		return m.RegistrationTimestamp
	}
	return 0
}

func (m *User) GetFollowers() []string {
	if m != nil {
		return m.Followers
	}
	return nil
}

func (m *User) GetFollowing() []string {
	if m != nil {
		return m.Following
	}
	return nil
}

func (m *User) GetTweets() []int64 {
	if m != nil {
		return m.Tweets
	}
	return nil
}

type EmptyReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyReply) Reset()         { *m = EmptyReply{} }
func (m *EmptyReply) String() string { return proto.CompactTextString(m) }
func (*EmptyReply) ProtoMessage()    {}
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{1}
}

func (m *EmptyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyReply.Unmarshal(m, b)
}
func (m *EmptyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyReply.Marshal(b, m, deterministic)
}
func (m *EmptyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyReply.Merge(m, src)
}
func (m *EmptyReply) XXX_Size() int {
	return xxx_messageInfo_EmptyReply.Size(m)
}
func (m *EmptyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyReply.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyReply proto.InternalMessageInfo

type CreateRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Firstname            string   `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{2}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateRequest) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *CreateRequest) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *CreateRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type DeleteRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{3}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetSummaryRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSummaryRequest) Reset()         { *m = GetSummaryRequest{} }
func (m *GetSummaryRequest) String() string { return proto.CompactTextString(m) }
func (*GetSummaryRequest) ProtoMessage()    {}
func (*GetSummaryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{4}
}

func (m *GetSummaryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSummaryRequest.Unmarshal(m, b)
}
func (m *GetSummaryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSummaryRequest.Marshal(b, m, deterministic)
}
func (m *GetSummaryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSummaryRequest.Merge(m, src)
}
func (m *GetSummaryRequest) XXX_Size() int {
	return xxx_messageInfo_GetSummaryRequest.Size(m)
}
func (m *GetSummaryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSummaryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSummaryRequest proto.InternalMessageInfo

func (m *GetSummaryRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetSummaryReply struct {
	Username              string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Firstname             string   `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname              string   `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Description           string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	RegistrationTimestamp int64    `protobuf:"varint,5,opt,name=registration_timestamp,json=registrationTimestamp,proto3" json:"registration_timestamp,omitempty"`
	FollowersCount        int64    `protobuf:"varint,6,opt,name=followers_count,json=followersCount,proto3" json:"followers_count,omitempty"`
	FollowingCount        int64    `protobuf:"varint,7,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	TweetsCount           int64    `protobuf:"varint,8,opt,name=tweets_count,json=tweetsCount,proto3" json:"tweets_count,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *GetSummaryReply) Reset()         { *m = GetSummaryReply{} }
func (m *GetSummaryReply) String() string { return proto.CompactTextString(m) }
func (*GetSummaryReply) ProtoMessage()    {}
func (*GetSummaryReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{5}
}

func (m *GetSummaryReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSummaryReply.Unmarshal(m, b)
}
func (m *GetSummaryReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSummaryReply.Marshal(b, m, deterministic)
}
func (m *GetSummaryReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSummaryReply.Merge(m, src)
}
func (m *GetSummaryReply) XXX_Size() int {
	return xxx_messageInfo_GetSummaryReply.Size(m)
}
func (m *GetSummaryReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSummaryReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetSummaryReply proto.InternalMessageInfo

func (m *GetSummaryReply) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetSummaryReply) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *GetSummaryReply) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *GetSummaryReply) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetSummaryReply) GetRegistrationTimestamp() int64 {
	if m != nil {
		return m.RegistrationTimestamp
	}
	return 0
}

func (m *GetSummaryReply) GetFollowersCount() int64 {
	if m != nil {
		return m.FollowersCount
	}
	return 0
}

func (m *GetSummaryReply) GetFollowingCount() int64 {
	if m != nil {
		return m.FollowingCount
	}
	return 0
}

func (m *GetSummaryReply) GetTweetsCount() int64 {
	if m != nil {
		return m.TweetsCount
	}
	return 0
}

type GetUsersRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Role                 Role     `protobuf:"varint,2,opt,name=role,proto3,enum=users.Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersRequest) Reset()         { *m = GetUsersRequest{} }
func (m *GetUsersRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersRequest) ProtoMessage()    {}
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{6}
}

func (m *GetUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersRequest.Unmarshal(m, b)
}
func (m *GetUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersRequest.Marshal(b, m, deterministic)
}
func (m *GetUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersRequest.Merge(m, src)
}
func (m *GetUsersRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersRequest.Size(m)
}
func (m *GetUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersRequest proto.InternalMessageInfo

func (m *GetUsersRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetUsersRequest) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_Follower
}

type GetUsersReply struct {
	// Types that are valid to be assigned to Reply:
	//	*GetUsersReply_User
	//	*GetUsersReply_Error
	Reply                isGetUsersReply_Reply `protobuf_oneof:"reply"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetUsersReply) Reset()         { *m = GetUsersReply{} }
func (m *GetUsersReply) String() string { return proto.CompactTextString(m) }
func (*GetUsersReply) ProtoMessage()    {}
func (*GetUsersReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{7}
}

func (m *GetUsersReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersReply.Unmarshal(m, b)
}
func (m *GetUsersReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersReply.Marshal(b, m, deterministic)
}
func (m *GetUsersReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersReply.Merge(m, src)
}
func (m *GetUsersReply) XXX_Size() int {
	return xxx_messageInfo_GetUsersReply.Size(m)
}
func (m *GetUsersReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersReply proto.InternalMessageInfo

type isGetUsersReply_Reply interface {
	isGetUsersReply_Reply()
}

type GetUsersReply_User struct {
	User *User `protobuf:"bytes,1,opt,name=user,proto3,oneof"`
}

type GetUsersReply_Error struct {
	Error bool `protobuf:"varint,2,opt,name=error,proto3,oneof"`
}

func (*GetUsersReply_User) isGetUsersReply_Reply() {}

func (*GetUsersReply_Error) isGetUsersReply_Reply() {}

func (m *GetUsersReply) GetReply() isGetUsersReply_Reply {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (m *GetUsersReply) GetUser() *User {
	if x, ok := m.GetReply().(*GetUsersReply_User); ok {
		return x.User
	}
	return nil
}

func (m *GetUsersReply) GetError() bool {
	if x, ok := m.GetReply().(*GetUsersReply_Error); ok {
		return x.Error
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetUsersReply) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetUsersReply_User)(nil),
		(*GetUsersReply_Error)(nil),
	}
}

type FollowRequest struct {
	Action               FollowRequest_Action `protobuf:"varint,1,opt,name=action,proto3,enum=users.FollowRequest_Action" json:"action,omitempty"`
	Follower             string               `protobuf:"bytes,2,opt,name=follower,proto3" json:"follower,omitempty"`
	Followed             string               `protobuf:"bytes,3,opt,name=followed,proto3" json:"followed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FollowRequest) Reset()         { *m = FollowRequest{} }
func (m *FollowRequest) String() string { return proto.CompactTextString(m) }
func (*FollowRequest) ProtoMessage()    {}
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{8}
}

func (m *FollowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowRequest.Unmarshal(m, b)
}
func (m *FollowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowRequest.Marshal(b, m, deterministic)
}
func (m *FollowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowRequest.Merge(m, src)
}
func (m *FollowRequest) XXX_Size() int {
	return xxx_messageInfo_FollowRequest.Size(m)
}
func (m *FollowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FollowRequest proto.InternalMessageInfo

func (m *FollowRequest) GetAction() FollowRequest_Action {
	if m != nil {
		return m.Action
	}
	return FollowRequest_Follow
}

func (m *FollowRequest) GetFollower() string {
	if m != nil {
		return m.Follower
	}
	return ""
}

func (m *FollowRequest) GetFollowed() string {
	if m != nil {
		return m.Followed
	}
	return ""
}

type UpdateTweetsRequest struct {
	Action               UpdateTweetsRequest_Action `protobuf:"varint,1,opt,name=action,proto3,enum=users.UpdateTweetsRequest_Action" json:"action,omitempty"`
	Username             string                     `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Tweet                []int64                    `protobuf:"varint,3,rep,packed,name=tweet,proto3" json:"tweet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *UpdateTweetsRequest) Reset()         { *m = UpdateTweetsRequest{} }
func (m *UpdateTweetsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTweetsRequest) ProtoMessage()    {}
func (*UpdateTweetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{9}
}

func (m *UpdateTweetsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTweetsRequest.Unmarshal(m, b)
}
func (m *UpdateTweetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTweetsRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTweetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTweetsRequest.Merge(m, src)
}
func (m *UpdateTweetsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTweetsRequest.Size(m)
}
func (m *UpdateTweetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTweetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTweetsRequest proto.InternalMessageInfo

func (m *UpdateTweetsRequest) GetAction() UpdateTweetsRequest_Action {
	if m != nil {
		return m.Action
	}
	return UpdateTweetsRequest_Add
}

func (m *UpdateTweetsRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateTweetsRequest) GetTweet() []int64 {
	if m != nil {
		return m.Tweet
	}
	return nil
}

type GenericUpdateReply struct {
	Code                 []GenericUpdateReply_Code `protobuf:"varint,1,rep,packed,name=code,proto3,enum=users.GenericUpdateReply_Code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GenericUpdateReply) Reset()         { *m = GenericUpdateReply{} }
func (m *GenericUpdateReply) String() string { return proto.CompactTextString(m) }
func (*GenericUpdateReply) ProtoMessage()    {}
func (*GenericUpdateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{10}
}

func (m *GenericUpdateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericUpdateReply.Unmarshal(m, b)
}
func (m *GenericUpdateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericUpdateReply.Marshal(b, m, deterministic)
}
func (m *GenericUpdateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericUpdateReply.Merge(m, src)
}
func (m *GenericUpdateReply) XXX_Size() int {
	return xxx_messageInfo_GenericUpdateReply.Size(m)
}
func (m *GenericUpdateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericUpdateReply.DiscardUnknown(m)
}

var xxx_messageInfo_GenericUpdateReply proto.InternalMessageInfo

func (m *GenericUpdateReply) GetCode() []GenericUpdateReply_Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func init() {
	proto.RegisterEnum("users.Role", Role_name, Role_value)
	proto.RegisterEnum("users.FollowRequest_Action", FollowRequest_Action_name, FollowRequest_Action_value)
	proto.RegisterEnum("users.UpdateTweetsRequest_Action", UpdateTweetsRequest_Action_name, UpdateTweetsRequest_Action_value)
	proto.RegisterEnum("users.GenericUpdateReply_Code", GenericUpdateReply_Code_name, GenericUpdateReply_Code_value)
	proto.RegisterType((*User)(nil), "users.User")
	proto.RegisterType((*EmptyReply)(nil), "users.EmptyReply")
	proto.RegisterType((*CreateRequest)(nil), "users.CreateRequest")
	proto.RegisterType((*DeleteRequest)(nil), "users.DeleteRequest")
	proto.RegisterType((*GetSummaryRequest)(nil), "users.GetSummaryRequest")
	proto.RegisterType((*GetSummaryReply)(nil), "users.GetSummaryReply")
	proto.RegisterType((*GetUsersRequest)(nil), "users.GetUsersRequest")
	proto.RegisterType((*GetUsersReply)(nil), "users.GetUsersReply")
	proto.RegisterType((*FollowRequest)(nil), "users.FollowRequest")
	proto.RegisterType((*UpdateTweetsRequest)(nil), "users.UpdateTweetsRequest")
	proto.RegisterType((*GenericUpdateReply)(nil), "users.GenericUpdateReply")
}

func init() {
	proto.RegisterFile("users.proto", fileDescriptor_030765f334c86cea)
}

var fileDescriptor_030765f334c86cea = []byte{
	// 740 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0x8e, 0xe3, 0xc4, 0x49, 0x27, 0x49, 0x9b, 0xee, 0xe9, 0x89, 0xdc, 0x9c, 0xa3, 0x73, 0x52,
	0xdf, 0x10, 0x81, 0x9a, 0x40, 0xaa, 0x5e, 0x00, 0x12, 0xa2, 0xff, 0xe5, 0x06, 0x24, 0xb7, 0xbd,
	0xe1, 0xa6, 0x72, 0xed, 0x6d, 0x58, 0xd5, 0xf6, 0x9a, 0xdd, 0x0d, 0x51, 0x78, 0x01, 0xc4, 0x4b,
	0x20, 0x5e, 0x82, 0x27, 0xe3, 0x05, 0xd0, 0xee, 0xda, 0x8e, 0xd3, 0xa6, 0x52, 0xef, 0x10, 0x57,
	0xc9, 0xcc, 0x7c, 0x33, 0xfb, 0xed, 0xcc, 0xb7, 0x63, 0x68, 0x4c, 0x38, 0x66, 0x7c, 0x90, 0x30,
	0x2a, 0x28, 0xaa, 0x2a, 0xc3, 0xf9, 0x5a, 0x86, 0xca, 0x05, 0xc7, 0x0c, 0x75, 0xa1, 0x2e, 0x3d,
	0xb1, 0x17, 0x61, 0xdb, 0xe8, 0x19, 0xfd, 0x15, 0x37, 0xb7, 0xd1, 0xbf, 0xb0, 0x72, 0x4d, 0x18,
	0x17, 0x2a, 0x58, 0x56, 0xc1, 0xb9, 0x43, 0x66, 0x86, 0x5e, 0x1a, 0x34, 0x75, 0x66, 0x66, 0xa3,
	0x1e, 0x34, 0x02, 0xcc, 0x7d, 0x46, 0x12, 0x41, 0x68, 0x6c, 0x57, 0x54, 0xb8, 0xe8, 0x42, 0xbb,
	0xd0, 0x61, 0x78, 0x4c, 0xb8, 0x60, 0x9e, 0xb4, 0x2f, 0x05, 0x89, 0x30, 0x17, 0x5e, 0x94, 0xd8,
	0xd5, 0x9e, 0xd1, 0x37, 0xdd, 0xbf, 0x8b, 0xd1, 0xf3, 0x2c, 0xa8, 0x28, 0xd1, 0x30, 0xa4, 0x53,
	0xcc, 0xb8, 0x6d, 0xf5, 0x4c, 0x45, 0x29, 0x73, 0xcc, 0xa3, 0x24, 0x1e, 0xdb, 0xb5, 0x62, 0x94,
	0xc4, 0x63, 0xd4, 0x01, 0x4b, 0x4c, 0x31, 0x16, 0xdc, 0xae, 0xf7, 0xcc, 0xbe, 0xe9, 0xa6, 0x96,
	0xd3, 0x04, 0x38, 0x8a, 0x12, 0x31, 0x73, 0x71, 0x12, 0xce, 0x9c, 0x2f, 0x06, 0xb4, 0x0e, 0x18,
	0xf6, 0x04, 0x76, 0xf1, 0xc7, 0x09, 0xe6, 0xe2, 0x77, 0xb5, 0xc8, 0x79, 0x02, 0xad, 0x43, 0x1c,
	0xe2, 0x07, 0x11, 0x71, 0x86, 0xb0, 0x7e, 0x82, 0xc5, 0xd9, 0x24, 0x8a, 0x3c, 0x36, 0x7b, 0x48,
	0xc2, 0x8f, 0x32, 0xac, 0x15, 0x33, 0x92, 0x70, 0xf6, 0xa7, 0x89, 0xe1, 0x11, 0xac, 0xe5, 0xb3,
	0xbf, 0xf4, 0xe9, 0x24, 0x16, 0xb6, 0xa5, 0xf0, 0xab, 0xb9, 0xfb, 0x40, 0x7a, 0xe7, 0x40, 0x12,
	0x8f, 0x53, 0x60, 0xad, 0x08, 0x24, 0xf1, 0x58, 0x03, 0xb7, 0xa0, 0xa9, 0x45, 0x91, 0xa2, 0xea,
	0x0a, 0xd5, 0xd0, 0x3e, 0x05, 0x71, 0xde, 0xaa, 0xb6, 0xc9, 0xb7, 0xc3, 0x1f, 0x22, 0x90, 0xff,
	0xa1, 0xc2, 0x68, 0xa8, 0x3b, 0xb6, 0x3a, 0x6a, 0x0c, 0xf4, 0x5b, 0x74, 0x69, 0x88, 0x5d, 0x15,
	0x70, 0xce, 0xa0, 0x35, 0xaf, 0x27, 0x87, 0xb0, 0x05, 0x15, 0x09, 0x52, 0x95, 0x1a, 0x79, 0x86,
	0x04, 0x9c, 0x96, 0x5c, 0x15, 0x42, 0x1d, 0xa8, 0x62, 0xc6, 0x28, 0x53, 0x55, 0xeb, 0xa7, 0x25,
	0x57, 0x9b, 0xfb, 0x35, 0xa8, 0x32, 0x25, 0xe2, 0xef, 0x06, 0xb4, 0x8e, 0xd5, 0xd5, 0x32, 0x8e,
	0x3b, 0x60, 0x79, 0xbe, 0xea, 0xbf, 0xa1, 0x98, 0xfc, 0x93, 0xd6, 0x5d, 0x40, 0x0d, 0xf6, 0x14,
	0xc4, 0x4d, 0xa1, 0xf2, 0x62, 0x59, 0x27, 0xd3, 0x91, 0xe7, 0x76, 0x21, 0x16, 0x64, 0x13, 0xcf,
	0x6c, 0xc7, 0x01, 0x4b, 0x57, 0x42, 0x00, 0x96, 0x3e, 0xa1, 0x5d, 0x42, 0x4d, 0xa8, 0x5f, 0xc4,
	0x1a, 0xd3, 0x36, 0x9c, 0x6f, 0x06, 0xfc, 0x75, 0x91, 0x04, 0x9e, 0xc0, 0xe7, 0xaa, 0xbb, 0x19,
	0xd1, 0xe7, 0xb7, 0x88, 0x6e, 0x65, 0x0d, 0xb8, 0x8b, 0x5d, 0x42, 0x37, 0x9f, 0x43, 0xf9, 0xd6,
	0x1c, 0x36, 0xa0, 0xaa, 0xa6, 0x68, 0x9b, 0xea, 0xed, 0x6b, 0xc3, 0xe9, 0xe6, 0x44, 0x6b, 0x60,
	0xee, 0x05, 0x41, 0xbb, 0x24, 0xff, 0x1c, 0xe2, 0xb0, 0x6d, 0x38, 0x3e, 0xa0, 0x13, 0x1c, 0x63,
	0x46, 0x7c, 0x7d, 0xb4, 0x9e, 0xce, 0x08, 0x2a, 0x3e, 0x0d, 0xe4, 0x9c, 0xcd, 0xfe, 0xea, 0xe8,
	0xbf, 0x94, 0xdc, 0x5d, 0xe0, 0xe0, 0x80, 0x06, 0xd8, 0x55, 0x58, 0x67, 0x13, 0x2a, 0xd2, 0x42,
	0x16, 0x94, 0xdf, 0xdd, 0xb4, 0x4b, 0x68, 0x05, 0xaa, 0x47, 0x72, 0x5e, 0x6d, 0xe3, 0xb1, 0x03,
	0x15, 0xa9, 0x05, 0xd9, 0x9b, 0xe3, 0xb4, 0xb3, 0xba, 0x53, 0xa9, 0x15, 0xb4, 0x8d, 0xd1, 0xcf,
	0x32, 0x54, 0x95, 0x3e, 0xd0, 0x2e, 0x80, 0x5e, 0x4d, 0x6a, 0x75, 0x6f, 0xa4, 0x87, 0x2f, 0x6c,
	0xab, 0xee, 0x7a, 0xea, 0x9d, 0xaf, 0x34, 0x99, 0xa6, 0x17, 0xc9, 0x42, 0xda, 0xc2, 0x6e, 0x59,
	0x96, 0x76, 0x2c, 0x1b, 0xa0, 0x94, 0xf9, 0x26, 0xbe, 0xa6, 0xe9, 0xa2, 0x40, 0x76, 0x7e, 0xe5,
	0x5b, 0xdb, 0xa6, 0xdb, 0x59, 0x12, 0x91, 0x75, 0x5e, 0x40, 0x3d, 0x53, 0x38, 0x2a, 0x60, 0x8a,
	0x4f, 0xa8, 0xbb, 0x71, 0xc7, 0x9f, 0x84, 0xb3, 0xa7, 0x06, 0x7a, 0x96, 0xe9, 0x27, 0xa7, 0xbd,
	0x20, 0xd8, 0x65, 0xb4, 0x8f, 0xa0, 0x59, 0xd4, 0x0a, 0xea, 0xde, 0x2f, 0xa0, 0xee, 0xe6, 0xbd,
	0xf3, 0xdb, 0x7f, 0xfd, 0xfe, 0xd5, 0x98, 0x88, 0x0f, 0x93, 0xab, 0x81, 0x4f, 0xa3, 0x61, 0x48,
	0x30, 0xa3, 0x9f, 0x87, 0x01, 0x49, 0xf8, 0xb6, 0x4f, 0x27, 0x8c, 0xe3, 0x29, 0x65, 0x37, 0xdb,
	0x62, 0x4a, 0x84, 0xc0, 0x6c, 0xa8, 0xaa, 0x5c, 0x72, 0xcc, 0x3e, 0x11, 0x1f, 0xbf, 0x54, 0x5f,
	0x5a, 0x7e, 0x65, 0xa9, 0xdf, 0x9d, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x77, 0x7b, 0x41, 0x3e,
	0x80, 0x07, 0x00, 0x00,
}
